[package]
name = "uScript"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
serde = { version = "1.0.163", features = ["derive"] }
toml = "0.7.4"
toml_edit = "0.19.9"
